name: Build and Push Base Image

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:
    inputs: 
      id: 
        description: 'run identifier'
        required: false

jobs:
  build:
    runs-on: [sre-runner]
    steps:
      - name: echo distinct ID ${{ github.event.inputs.id }}
        run: echo ${{ github.event.inputs.id }}    

      - uses: actions/checkout@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get changed files
        id: changes
        uses: tj-actions/changed-files@v44
      
      - name: Build and Push Alpine-Node Images
        run: |
          cd alpine-node
          for NODE_VERSION in 16 24; do
            sh build.sh $NODE_VERSION
            docker push prasathmahendraraja/alpine-node:$NODE_VERSION
          done

      - name: Build and Push Alpine-Node-Git Images
        run: |
          cd alpine-node-git
          for NODE_VERSION in 16 24; do
            sh build.sh $NODE_VERSION
            docker push prasathmahendraraja/alpine-node-git:$NODE_VERSION
          done
      
      - name: Build and Push Alpine-Node-Java Base Image
        run: |
          cd alpine-node-java
          for NODE_VERSION in 16 24; do
            sh build.sh $NODE_VERSION
            docker push prasathmahendraraja/alpine-node-java:$NODE_VERSION
          done

      - name: Build and Push Node-alpine-python3-sqlite3-chromedriver-git Base Image
        run: |
          cd node-alpine-python3-sqlite3-chromedriver-git
          for NODE_VERSION in 16 24; do
            sh build.sh $NODE_VERSION
            docker push prasathmahendraraja/node:$NODE_VERSION-alpine-python3-sqlite3-chromedriver-git
          done

      - name: Build and Push JNLP Base Image
        run: |
          cd jnlp
          for NODE_VERSION in 16 24; do
            sh build.sh $NODE_VERSION
            docker push prasathmahendraraja/jnlp:$NODE_VERSION
          done

      - name: Build and Push Alpine-Node-Java17 Base Image
        run: |
          cd alpine-node-java17
          for NODE_VERSION in 16 24; do
            sh build.sh $NODE_VERSION
            docker push prasathmahendraraja/alpine-node-java17:$NODE_VERSION
          done          